In [3]:
import numpy as np

#Create a null vector of size 10 but the fifth value which is 1

zero = np.zeros(10)
zero[4] =1
zero

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

In [6]:
#Create a vector with values ranging from 10 to 49

ten = np.arange(10,50)
ten

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [20]:
ten[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [22]:
#Create a 3x3 matrix with values ranging from 0 to 8 

threes = np.arange(0,9).reshape(3,3)
threes


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
#Find indices of non-zero elements from [1,2,0,0,4,0] 
a = [1,2,0,0,4,0] 

np.nonzero(a)

(array([0, 1, 4]),)

In [31]:
#Create a 3x3 identity matrix

np.eye(3,3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [36]:
rano= np.random.random((3,3,3))
rano

array([[[ 0.43239277,  0.16325608,  0.13373613],
        [ 0.10796071,  0.17091279,  0.49141549],
        [ 0.98429881,  0.40898636,  0.73809323]],

       [[ 0.9712532 ,  0.37144318,  0.11993556],
        [ 0.83628218,  0.28993339,  0.64588278],
        [ 0.01978356,  0.79783205,  0.12415319]],

       [[ 0.3942719 ,  0.78283054,  0.39943713],
        [ 0.68122238,  0.11707355,  0.96680367],
        [ 0.08626102,  0.29878603,  0.03150692]]])

In [40]:
#Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

random2 = np.random.random((10,10))
zmin,zmax = np.min(random2), np.max(random2)
print zmin,zmax 

0.00640415900347 0.995657164508


In [46]:
#Create a random vector of size 30 and find the mean value
b = np.random.random(30)
np.mean(b)

0.47519843484368651

In [53]:
#Create a 2d array with 1 on the border and 0 inside

z = np.ones((10,10))

z[1:-1,1:-1] = 0

z

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [54]:
0 * np.nan

nan

In [63]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

0.30000000000000004

In [82]:
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

Z = np.diag(1+np.arange(4),k=-1)
print(Z)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
